PREFIX n: <https://nap.nprod.net/>

SELECT DISTINCT ?compound ?compound_name (count(distinct ?pharmacy) as ?occurrences)

WHERE {
?pharmacy n:has_worktype ?worktype;
          n:has_organism ?organism.
?organism n:participatesIn ?citation.
?pharmacy n:has_participant ?compound.
?compound a n:compound;
          n:name ?compound_name.
?worktype n:code ?worktypecode.

VALUES ?worktypecode {
"AK" # LIPID ANALYSIS REPORTED FOR
"AM" # IDENTIFICATION IN BY TLC AFTER ACID HYDROLYSIS
"A8" # ISOLATION OF COMPOUND WITH UNKNOWN STRUCTURE
"BT" # ISOLATION FROM DURING BIOSYNTHESIS STUDY
"BX" # IDENTIFICATION IN BY GC/MS AFTER ACID HYDROLYSIS
"B1" # ISOLATION OF A COMPOUND WITH NOVEL STRUCTURE
"DC" # IDENTIFICATION IN BY DROPLET CCD
"EL" # ELECTROPHORESISa
"ET" # COMPOUND ISOLATED FROM FOLLOWING ENZYMATIC HYD...
"FM" # FLUORESCENT MICROSCOPIC IDENTIFICATION OF
"GF" # IDENTIFICATION IN BY CMR SPECTROSCOPY
"HK" # ISOLATION OF NEW COMPOUND FOLLOWING SAPONIFICA...
"HL" # ISOLATION OF NEW COMPOUND FOLLOWING ACID HYDRO...
"HM" # ISOLATION OF NEW COMPOUND FOLLOWING ENZYMATIC ...
"HN" # IDENTIFICATION IN BY RIA
"PA" # ISOLATION OF PHYTOALEXIN FROM
"PC" # PAPER CHROMATOGRAPHIC PATTERN REPORTED FOR
"PH" # IDENTIFICATION IN BY PC AFTER ACID HYDROLYSIS
"P9" # ISOLATION OF A PHYTOALEXIN FROM
"RC" # PRESENT IN (REVIEW)
"T1" # IDENTIFICATION IN BY TLC
"T2" # IDENTIFICATION IN BY GLC
"T3" # IDENTIFICATION IN BY GC/MS
"T4" # IDENTIFICATION IN BY PAPER CHROMATOGRAPHY
"T5" # IDENTIFICATION IN BY UV SHIFTS AFTER ADDITION ...
"T6" # IDENTIFICATION IN BY GLC AFTER SAPONIFICATION
"T7" # IDENTIFICATION IN AFTER SAPONIFICATION
"T8" # SPECTROPHOTOMETRIC QUANTIFICATION OF IN
"T9" # IDENTIFICATION IN BY HPLC
"UA" # ISOLATION FROM AFTER SAPONIFICATION
"UB" # IDENTIFICATION IN BY COLOR REACTIONS
"UC" # IDENTIFICATION IN BY GLC AFTER ACID HYDROLYSIS
"11" # ISOLATION AND IDENTIFICATION OF
"13" # SEPARATION OF (EXCEPT OILS, VENOM, PROTEINS, F...
"14" # IDENTIFICATION OF
"16" # ISOLATION AND IDENTIFICATION AFTER CHEMICAL TR...
"35" # ISOLATION AND IDENTIFICATION OF AN ARTIFACT
"TA" # IDENTIFICATION IN BY HPLC/MS
"TB" # IDENTIFICATION IN BY LC/MS
"TC" # IDENTIFICATION IN BY CONTINUOUS FLOW FAB
"LM" # IDENTIFICATION IN BY LICHEN MASS SPECTROMETRY
"AR" # IDENTIFICATION IN AFTER ACID HYDROLYSIS
"SN" # ISOLATION OF A NEW COMPOUND USING SUPERCRITICA...
"SK" # ISOLATION OF A KNOWN COMPOUND USING SUPERCRITI...
"CB" # ISOLATION BY CCC
"CC" # IDENTIFIED IN BY CAPILLARY CHROMATOGRAPHY
}
}

GROUP BY ?compound ?compound_name
ORDER BY DESC(?occurrences)
LIMIT 500
